### ISSUE TITLE
CEW not working with Ledger Nano S FW 1.5.5 (Uncaught error)

### ISSUE THREAD

**Issue by cypheron** [ethereumclassic/etherwallet#71]
CEW is not working with the newest ledger firmware 1.5.5. Instead of connecting to the ledger wallet, nothing happens on-screen and an error message is shown in the console (see below).

### Steps to reproduce
In CEW, click on "Send & Receive", select "Ledger" and then "Connect to ledger wallet".

### Error Logs
`Uncaught (in promise) TransportStatusError {name: "TransportStatusError", message: "Ledger device: UNKNOWN_ERROR (0x6804)", stack: "Error↵    at new TransportStatusError (https://wal…callisto.network/js/etherwallet-master.js:2612:97", statusCode: 26628, statusText: "UNKNOWN_ERROR"}message: "Ledger device: UNKNOWN_ERROR (0x6804)"name: "TransportStatusError"stack: "Error↵    at new TransportStatusError (https://wallet.callisto.network/js/etherwallet-master.js:435:399)↵    at TransportU2F._callee$ (https://wallet.callisto.network/js/etherwallet-master.js:438:7)↵    at tryCatch (https://wallet.callisto.network/js/etherwallet-master.js:2627:81)↵    at Generator.invoke [as _invoke] (https://wallet.callisto.network/js/etherwallet-master.js:2645:36)↵    at Generator.prototype.(anonymous function) [as next] (https://wallet.callisto.network/js/etherwallet-master.js:2632:458)↵    at step (https://wallet.callisto.network/js/etherwallet-master.js:2611:179)↵    at https://wallet.callisto.network/js/etherwallet-master.js:2612:97"statusCode: 26628statusText: "UNKNOWN_ERROR"__proto__: Error
    at Object.<anonymous> (https://wallet.callisto.network/js/etherwallet-master.js:436:32)
    at Object.203.babel-runtime/core-js/get-iterator (https://wallet.callisto.network/js/etherwallet-master.js:442:1660)
    at o (https://wallet.callisto.network/js/etherwallet-master.js:1:265)
    at https://wallet.callisto.network/js/etherwallet-master.js:1:316
    at Object.<anonymous> (https://wallet.callisto.network/js/etherwallet-master.js:411:1011)
    at Object.202.@ledgerhq/hw-transport (https://wallet.callisto.network/js/etherwallet-master.js:431:811)
    at o (https://wallet.callisto.network/js/etherwallet-master.js:1:265)
    at https://wallet.callisto.network/js/etherwallet-master.js:1:316
    at Object.<anonymous> (https://wallet.callisto.network/js/etherwallet-master.js:357:418)
    at Object.196../contract (https://wallet.callisto.network/js/etherwallet-master.js:385:693)stack: "Error↵    at Object.<anonymous> (https://wallet.callisto.network/js/etherwallet-master.js:436:32)↵    at Object.203.babel-runtime/core-js/get-iterator (https://wallet.callisto.network/js/etherwallet-master.js:442:1660)↵    at o (https://wallet.callisto.network/js/etherwallet-master.js:1:265)↵    at https://wallet.callisto.network/js/etherwallet-master.js:1:316↵    at Object.<anonymous> (https://wallet.callisto.network/js/etherwallet-master.js:411:1011)↵    at Object.202.@ledgerhq/hw-transport (https://wallet.callisto.network/js/etherwallet-master.js:431:811)↵    at o (https://wallet.callisto.network/js/etherwallet-master.js:1:265)↵    at https://wallet.callisto.network/js/etherwallet-master.js:1:316↵    at Object.<anonymous> (https://wallet.callisto.network/js/etherwallet-master.js:357:418)↵    at Object.196../contract (https://wallet.callisto.network/js/etherwallet-master.js:385:693)"__proto__: Objectconstructor: ƒ Error()stackTraceLimit: 10arguments: (...)caller: (...)captureStackTrace: ƒ captureStackTrace()isError: ƒ isError()length: 1name: "Error"prototype: {constructor: ƒ, name: "Error", message: "", toString: ƒ}__proto__: ƒ ()[[Scopes]]: Scopes[0]message: ""name: "Error"toString: ƒ toString()__proto__: Object
Promise.then (async)
Transport.create.then.transport @ etherwallet-master.js:108
Promise.then (async)
$scope.scanLedger @ etherwallet-master.js:108
fn @ VM651:4
callback @ etherwallet-master.js:2135
$eval @ etherwallet-master.js:1840
$apply @ etherwallet-master.js:1841
(anonymous) @ etherwallet-master.js:2135
defaultHandlerWrapper @ etherwallet-master.js:1142
eventHandler @ etherwallet-master.js:1141`

### Using
Ledger Nano S FW 1.5.5
Ethereum App v 1.1.9
Google Chrome Stable (Latest)

**Comment by cypheron** [comment]
wrong repo
